name: Create Jira Ticket for Github Issue

on:
  issues:
    types: [opened, reopened]

jobs:
  issue-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue
        id: create_jira
        uses: actions/github-script@v9
        with:
          script: |
            const baseUrl = process.env.JIRA_BASE_URL;
            const userEmail = process.env.JIRA_USER_EMAIL;
            const jiraToken = process.env.JIRA_API_TOKEN;
            const jiraProject = process.env.JIRA_PROJECT;
            const jiraIssueType = process.env.JIRA_ISSUE_TYPE;
            const jiraFields = JSON.parse(process.env.ISSUES_JIRA_FIELDS);

            let requestBody = JSON.stringify({
                fields: {
                    ...jiraFields,
                    "project": {
                        "key": jiraProject
                    },
                    "issuetype": {
                        "name": jiraIssueType
                    },
                    "summary": "Github | Issue | ${{ github.event.repository.name }} | ${{ github.event.issue.title }}",
                    "description": {
                        "version": 1,
                        "type": "doc",
                        "content": [
                            {
                                "type": "paragraph",
                                "content": [
                                    {
                                        "type": "text",
                                        "text": "Github Issue",
                                        "marks": [
                                            {
                                                "type": "strong"
                                            }
                                        ]
                                    },
                                    {
                                        "type": "text",
                                        "text": ":   "
                                    },
                                    {
                                        "type": "text",
                                        "text": "${{ github.event.issue.html_url }}",
                                        "marks": [
                                            {
                                                "type": "link",
                                                "attrs": {
                                                    "href": "${{ github.event.issue.html_url }}"
                                                }
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                "type": "paragraph",
                                "content": [
                                    {
                                        "type": "text",
                                        "text": "Description",
                                        "marks": [
                                            {
                                                "type": "strong"
                                            }
                                        ]
                                    },
                                    {
                                        "type": "text",
                                        "text": ":"
                                    }
                                ]
                            },
                            {
                                "type": "codeBlock",
                                "content": [
                                    {
                                        "type": "text",
                                        "text": `${{ github.event.issue.body }}`
                                    }
                                ]
                            }
                        ]
                    }
                }
            });

            const response = await fetch(`${baseUrl}/rest/api/3/issue`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Authorization': `Basic ${btoa(userEmail + ":" + jiraToken)}`
              },
              body: requestBody
            });
            if (!response.ok) {
              throw new Error(`JIRA API error! Status: ${response.status}`);
            }
            const data = await response.json();
            console.log('Jira Issue Created:', data.key);
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT: ${{ secrets.JIRA_PROJECT }}
          JIRA_ISSUE_TYPE: ${{ secrets.JIRA_ISSUE_TYPE }}
          ISSUES_JIRA_FIELDS: "${{ secrets.ISSUES_JIRA_FIELDS }}"
