name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
<<<<<<< HEAD
  security-sca:
=======
  security:
>>>>>>> upstream/next-feature-update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --fail-on=all
